export const ERRORS = {
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_REQUIRED: 'CATEGORY_REQUIRED',
  CATEGORY_TYPE_MISMATCH: 'CATEGORY_TYPE_MISMATCH',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  TRANSFER_SAME_ACCOUNT: 'TRANSFER_SAME_ACCOUNT',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  TRANSFER_INVALID: 'TRANSFER_INVALID',
} as const;
